# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-12 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('sleep_start', models.TimeField()),
                ('sleep_end', models.TimeField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Athlete')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.DateTimeField()),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('fat_percentage', models.FloatField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Athlete')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
